version: "3.7"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "2"

services:
  web:
    build:
      context: ./
      args:
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        TIOJ_KEY: $FETCH_KEY
    environment:
      - RAILS_ENV=production
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_ADDRESS
      - MAIL_HOSTNAME
      - MAIL_SENDER
      - ALLOW_REGISTER
    volumes:
      - /srv/ioic2024_tioj/web-td:/tioj/td
      - /srv/ioic2024_tioj/web-log:/tioj/log
      - /srv/ioic2024_tioj/public:/tioj/public
    depends_on:
      - db
    networks:
      - app
    ports:
      - "4002:4000"
    logging: *default-logging
    container_name: ioic2024_tioj_web
    restart: always
  db:
    image: mysql:8.0
    volumes:
      - /srv/ioic2024_tioj/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=tioj_production
    networks:
      - app
    logging: *default-logging
    container_name: ioic2024_tioj_db
    restart: always
  judge:
    build: https://github.com/TIOJ-INFOR-Online-Judge/tioj-judge.git#31228c2379edeff1ee27108ea6043d6c04fb83e5
    environment:
      TIOJ_URL: "http://localhost:4002"
      TIOJ_KEY: $FETCH_KEY
    volumes:
      - /srv/ioic2024_tioj/judge-td-pool:/var/lib/tioj-judge/td-pool
      - /srv/ioic2024_tioj/judge-testdata:/var/lib/tioj-judge/testdata
    tmpfs:
      - /tmp:exec
    privileged: true
    network_mode: host
    pid: host
    logging: *default-logging
    container_name: ioic2024_tioj_judge
    restart: always

networks:
  app:
